runtime: go113  # or go113 for Go 1.13 runtime (beta)
service: default
instance_class: F2

env_variables:
  DISCORD_WEBHOOK: "https://discordapp.com/api/webhooks/777754645363818496/5iZNWA6vvKRAh4k7zHEi437Yw24xyx3ZY44MJWDnpq7HUBEasNko7fn_LSpiHlB00Esb"
  MJ_APIKEY_PUBLIC: %MJ_APIKEY_PUBLIC%
  MJ_APIKEY_PRIVATE: %MJ_APIKEY_PRIVATE%
  TWITTER_BEARER_TOKEN: %TWITTER_BEARER_TOKEN%

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: auto