runtime: go113  # or go113 for Go 1.13 runtime (beta)
service: default
instance_class: F2

env_variables:
  DISCORD_WEBHOOK: "https://discordapp.com/api/webhooks/733168335948349471/HpMygarmZj-jphuBDi0JWbx2Hi1xvWwKD-pYt9QFuTeSCR8tvSyjNty-4kt1Kyp7E_GQ"
  MJ_APIKEY_PUBLIC: %MJ_APIKEY_PUBLIC%
  MJ_APIKEY_PRIVATE: %MJ_APIKEY_PRIVATE%

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: auto