runtime: go113  # or go113 for Go 1.13 runtime (beta)
service: default
instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  DISCORD_WEBHOOK: "https://discordapp.com/api/webhooks/733168335948349471/HpMygarmZj-jphuBDi0JWbx2Hi1xvWwKD-pYt9QFuTeSCR8tvSyjNty-4kt1Kyp7E_GQ"
  MJ_APIKEY_PUBLIC: "89c1f1993ca0ddbfa1492ef4a47744e4"
  MJ_APIKEY_PRIVATE: "22364305ea7f6b0d7553cba0f28ec6dd"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: auto